name: CI-develop

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1
    - name: Prepare Artifacts
      run: |
        mkdir artifacts
        mkdir artifacts/lib
        mkdir artifacts/images
        cp IctBaden.Stonehenge4/icon64.png artifacts/images
    - name: Build Core
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes4.md)
        echo Version=$version
        dotnet build --configuration Release ./IctBaden.Stonehenge4/IctBaden.Stonehenge4.csproj -p:AssemblyVersion=$version -p:Version=4.0
        cp IctBaden.Stonehenge4/bin/Release/net6.0/IctBaden.Stonehenge4.dll artifacts/lib
    - name: Build Kestrel
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes4.md)
        echo Version=$version
        dotnet build --configuration Release ./IctBaden.Stonehenge4.Kestrel/IctBaden.Stonehenge4.Kestrel.csproj -p:AssemblyVersion=$version -p:Version=4.0
        cp IctBaden.Stonehenge4.Kestrel/bin/Release/net6.0/IctBaden.Stonehenge4.Kestrel.dll artifacts/lib
    - name: Build Vue
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes4.md)
        echo Version=$version
        dotnet build --configuration Release ./IctBaden.Stonehenge4.Vue/IctBaden.Stonehenge4.Vue.csproj -p:AssemblyVersion=$version -p:Version=4.0
        cp IctBaden.Stonehenge4.Vue/bin/Release/net6.0/IctBaden.Stonehenge4.Vue.dll artifacts/lib
    - name: Build App
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes4.md)
        echo Version=$version
        dotnet build --configuration Release ./IctBaden.Stonehenge4.App/IctBaden.Stonehenge4.App.csproj -p:AssemblyVersion=$version -p:Version=4.0
        cp IctBaden.Stonehenge4.App/bin/Release/net6.0/IctBaden.Stonehenge4.App.dll artifacts/lib
    - name: Build AppDialog
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes4.md)
        echo Version=$version
        dotnet build --configuration Release ./IctBaden.Stonehenge4.AppDialog/IctBaden.Stonehenge4.App.csproj -p:AssemblyVersion=$version -p:Version=4.0
        cp IctBaden.Stonehenge4.App/bin/Release/net6.0/IctBaden.Stonehenge4.AppDialog.dll artifacts/lib
    - name: Build ChartsC3
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes4.md)
        echo Version=$version
        dotnet build --configuration Release ./IctBaden.Stonehenge4.ChartsC3/IctBaden.Stonehenge4.ChartsC3.csproj -p:AssemblyVersion=$version -p:Version=4.0
        cp IctBaden.Stonehenge4.ChartsC3/bin/Release/net6.0/IctBaden.Stonehenge4.ChartsC3.dll artifacts/lib
    - name: Build TreeView
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes4.md)
        echo Version=$version
        dotnet build --configuration Release ./IctBaden.Stonehenge4.ChartsC3/IctBaden.Stonehenge4.TreeView.csproj -p:AssemblyVersion=$version -p:Version=4.0
        cp IctBaden.Stonehenge4.ChartsC3/bin/Release/net6.0/IctBaden.Stonehenge4.TreeView.dll artifacts/lib
    - name: Test with dotnet
      env: 
        SkipPerformanceTests: true
      run: dotnet test ./Stonehenge4.sln --configuration Release
    - name: Pack Nuget
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes4.md)
        echo Version=$version
        cd artifacts
        nuget pack ../Stonehenge4.nuspec -BasePath . -Version $version
    - uses: actions/upload-artifact@v2
      with:
        name: Stonehenge4_develop
        path: artifacts
