name: CI-develop

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup dotnet 8.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
      
    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1
      
    - name: Prepare Artifacts
      run: |
        mkdir artifacts
        mkdir artifacts/lib
        mkdir artifacts/images
        cp IctBaden.Stonehenge4/icon64.png artifacts/images
        
    - name: Get Version Info
      run: |
        libMainVersion=4.0
        assemblyVersion=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes4.md)
        echo LibMainVersion=$libMainVersion
        echo AssemblyVersion=$assemblyVersion
        echo "LibMainVersion=$libMainVersion" >> $GITHUB_ENV
        echo "AssemblyVersion=$assemblyVersion" >> $GITHUB_ENV
        
    - name: Build Core
      run: |
        dotnet build --configuration Release ./IctBaden.Stonehenge4/IctBaden.Stonehenge4.csproj -p:AssemblyVersion=${{ env.AssemblyVersion }} -p:Version=${{ env.LibMainVersion }}
        cp IctBaden.Stonehenge4/bin/Release/net8.0/IctBaden.Stonehenge4.dll artifacts/lib
    - name: Build Kestrel
      run: |
        dotnet build --configuration Release ./IctBaden.Stonehenge4.Kestrel/IctBaden.Stonehenge4.Kestrel.csproj -p:AssemblyVersion=${{ env.AssemblyVersion }} -p:Version=${{ env.LibMainVersion }}
        cp IctBaden.Stonehenge4.Kestrel/bin/Release/net8.0/IctBaden.Stonehenge4.Kestrel.dll artifacts/lib
    - name: Build Vue
      run: |
        dotnet build --configuration Release ./IctBaden.Stonehenge4.Vue/IctBaden.Stonehenge4.Vue.csproj -p:AssemblyVersion=${{ env.AssemblyVersion }} -p:Version=${{ env.LibMainVersion }}
        cp IctBaden.Stonehenge4.Vue/bin/Release/net8.0/IctBaden.Stonehenge4.Vue.dll artifacts/lib
    - name: Build App
      run: |
        dotnet build --configuration Release ./IctBaden.Stonehenge4.App/IctBaden.Stonehenge4.App.csproj -p:AssemblyVersion=${{ env.AssemblyVersion }} -p:Version=${{ env.LibMainVersion }}
        cp IctBaden.Stonehenge4.App/bin/Release/net8.0/IctBaden.Stonehenge4.App.dll artifacts/lib
    - name: Build AppDialog
      run: |
        dotnet build --configuration Release ./IctBaden.Stonehenge4.AppDialog/IctBaden.Stonehenge4.AppDialog.csproj -p:AssemblyVersion=${{ env.AssemblyVersion }} -p:Version=${{ env.LibMainVersion }}
        cp IctBaden.Stonehenge4.AppDialog/bin/Release/net8.0/IctBaden.Stonehenge4.AppDialog.dll artifacts/lib
    - name: Build ChartsC3
      run: |
        dotnet build --configuration Release ./IctBaden.Stonehenge4.ChartsC3/IctBaden.Stonehenge4.ChartsC3.csproj -p:AssemblyVersion=${{ env.AssemblyVersion }} -p:Version=${{ env.LibMainVersion }}
        cp IctBaden.Stonehenge4.ChartsC3/bin/Release/net8.0/IctBaden.Stonehenge4.ChartsC3.dll artifacts/lib
    - name: Build TreeView
      run: |
        dotnet build --configuration Release ./IctBaden.Stonehenge4.TreeView/IctBaden.Stonehenge4.TreeView.csproj -p:AssemblyVersion=${{ env.AssemblyVersion }} -p:Version=${{ env.LibMainVersion }}
        cp IctBaden.Stonehenge4.TreeView/bin/Release/net8.0/IctBaden.Stonehenge4.TreeView.dll artifacts/lib
    - name: Build Forms
      run: |
        dotnet build --configuration Release ./IctBaden.Stonehenge4.Forms/IctBaden.Stonehenge4.Forms.csproj -p:AssemblyVersion=${{ env.AssemblyVersion }} -p:Version=${{ env.LibMainVersion }}
        cp IctBaden.Stonehenge4.Forms/bin/Release/net8.0/IctBaden.Stonehenge4.Forms.dll artifacts/lib
    - name: Build Mermaid
      run: |
        dotnet build --configuration Release ./IctBaden.Stonehenge4.Mermaid/IctBaden.Stonehenge4.Mermaid.csproj -p:AssemblyVersion=${{ env.AssemblyVersion }} -p:Version=${{ env.LibMainVersion }}
        cp IctBaden.Stonehenge4.Mermaid/bin/Release/net8.0/IctBaden.Stonehenge4.Mermaid.dll artifacts/lib
        
    - name: Test with dotnet
      env: 
        SkipPerformanceTests: true
      run: dotnet test ./Stonehenge4.sln --configuration Release
      
    - name: Pack Nuget
      run: |
        cd artifacts
        nuget pack ../Stonehenge4.nuspec -BasePath . -Version ${{ env.AssemblyVersion }}
        
    - uses: actions/upload-artifact@v2
      with:
        name: Stonehenge4_develop
        path: artifacts
